[project]
name = "transformers-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "nltk>=3.9.1",
    "polars>=1.31.0",
    "torch>=2.7.1",
    "tqdm>=4.67.1",
]
